DAOS-11151 build: Upgrade PMDK to 1.12.0
daos-stack/pmdk-pkg pull request #23
Opened 2022-07-21 14:50 UTC by jolivier23

There is a serious longstanding issue in PMDK that can be fixed
by https://github.com/pmem/pmdk/pull/5470.   Upgrade to 1.12.0
first to tickle out any bugs that may cause.

Signed-off-by: Jeff Olivier <jeffrey.v.olivier@intel.com>

2022-07-22 01:38 UTC, brianjmurrell commented
The rpmlint output, oh the horror!  Lots of duplicate files I see.  I think `%fdupes` is provided to resolve those.

2022-07-22 15:47 UTC, brianjmurrell commented on pmdk.spec
> +%fdupes %{buildroot}/%{_prefix}
Hrm.  This doesn't seem to be resolving the dups.  Can you add:

```
fdupes -q -n -r -p
```
before and after this `%fdupes` line above so that we can see what `fdupes` is outputting.

2022-07-22 16:20 UTC, brianjmurrell commented on pmdk.spec
>  License:	BSD-3-Clause
This needs changing to simply `BSD`.

2022-07-25 13:18 UTC, brianjmurrell requested changes

2022-07-25 13:18 UTC, brianjmurrell commented on Jenkinsfile
> +                'pipeline-lib@bmurrell/test-images']) _
-1 until this is removed just to prevent an accidental landing.

2022-07-25 13:18 UTC, brianjmurrell commented on debian/rules
> -	dh_auto_clean -- NDCTL_ENABLE=n
I'm a bit apprehensive about removing this.  Why is it necessary?

2022-07-25 13:18 UTC, brianjmurrell commented on pmdk.spec
> +sed -i 's/cmake/cmake3/' src/deps/miniasync/Makefile
This could be a bit more defensive:

```suggestion
sed -i -e 's/cmake\([^3]\)/cmake3\1/' src/deps/miniasync/Makefile
```

So that it won't make any future mistake of changing `cmake3` to `cmake33` if upstream changes `cmake` to `cmake3`.

2022-07-25 13:18 UTC, brianjmurrell commented on pmdk.spec
> +fdupes -q -n -r -p %{buildroot}/%{_prefix}
This will need removing once the duplicates issue has been resolved.  I still need to look into why that is still being flagged when `fdupes` appears to be doing it's job.

2022-07-25 13:18 UTC, brianjmurrell commented on pmdk.spec
> +fdupes -q -n -r -p %{buildroot}/%{_prefix}
Ditto.

2022-07-25 15:49 UTC, jolivier23 commented on debian/rules
> -	dh_auto_clean -- NDCTL_ENABLE=n
If you have an alternative that works, I'd appreciate it.   The issue is when this is there, the build fails due to missing packages.

2022-07-25 15:55 UTC, brianjmurrell commented on debian/rules
> -	dh_auto_clean -- NDCTL_ENABLE=n
Is there a build you can point me at that shows what the problem is with it in?

2022-07-25 23:37 UTC, jolivier23 commented on debian/rules
> -	dh_auto_clean -- NDCTL_ENABLE=n
https://build.hpdd.intel.com/blue/rest/organizations/jenkins/pipelines/daos-stack/pipelines/pmdk/branches/PR-23/runs/19/nodes/189/steps/307/log/?start=0

There are a bunch of them but this one seems to have it.  cmake isn't found.  It also has the other test issues.

2022-07-26 17:56 UTC, brianjmurrell commented on debian/rules
> -	dh_auto_clean -- NDCTL_ENABLE=n
This seems to happen before the _pbuilder chroot_ build is done.  I think you should be able to add `cmake` to https://github.com/daos-stack/pmdk/blob/f551d0321cb93e42dc3599a0542092dd9c8fb7db/packaging/Dockerfile.ubuntu.20.04#L20 to make it available to the `dh_auto_clean` target.

Honestly, this whole _pbuilder_ tool is a lot more rough than `mock` is for building RPMs.  I wonder if any better tools have been introduced for that since this deb build was written.

2022-07-27 14:24 UTC, brianjmurrell requested changes
Really great work @jolivier23.  Just a few remaining issues, mostly from previous reviews.

2022-07-27 14:24 UTC, brianjmurrell commented on Makefile
> +DL_VERSION    := 1.12.0
Hrm.  I never took note of this before.  This shouldn't be necessary.  https://github.com/daos-stack/pmdk/blob/4ba5d60d5827c7ab9e2f1a906df056f5b2d31d52/packaging/Makefile_packaging.mk#L150-L152 should determine this from the `VERSION` which is also automatically determined.

2022-07-27 14:24 UTC, brianjmurrell commented on debian/rules
> -	dh_auto_clean -- NDCTL_ENABLE=n
Did you try this?  Was it also unable to resolve this problem?

2022-07-27 14:24 UTC, brianjmurrell commented on debian/rules
> +	echo "Check skipped"
Was the check not working or just not at all valid any more?  It still seems to be part of the RPM build so guessing not the latter.

If the former, it looks like you could have just added `nocheck` to `DEB_BUILD_OPTIONS` somewhere near the top of this file with:

```
DEB_BUILD_OPTIONS += nocheck
```

But if the RPM build is still running the check, would it not be good to have the debian build run it also, if it's not a huge task.

2022-07-27 14:24 UTC, brianjmurrell commented on pmdk.spec
> +fdupes -q -n -r -p %{buildroot}/%{_prefix}
Still needs removing.

2022-07-27 14:24 UTC, brianjmurrell commented on pmdk.spec
> +fdupes -q -n -r -p %{buildroot}/%{_prefix}
Ditto.

2022-07-27 14:42 UTC, jolivier23 commented on debian/rules
> +	echo "Check skipped"
It wasn't working.   It has a bunch of python import errors and the old stuff (that John hacked in) wasn't sufficient for when I removed the rpmem stuff so I punted and removed it because I didn't want to spend more time on making it work.

2022-07-27 14:43 UTC, jolivier23 commented on debian/rules
> +	echo "Check skipped"
And no, what was originally there ran make clean before and failed.

2022-07-27 16:41 UTC, brianjmurrell requested changes
The DL_VERSION misdirect is the only issue left I think.

2022-07-27 16:41 UTC, brianjmurrell commented on Makefile
> +endif
I seem to have inadvertently misled you.  I meant you could remove setting `DL_VERSION` in this `Makefile` altogether and that the code I previously referenced was just showing you where it's determined automatically, just as a FYI.

```suggestion
```

2022-07-27 16:53 UTC, brianjmurrell approved these changes
Great effort @jolivier23!

2022-07-27 17:29 UTC, merged