DAOS-623 pmdk: Update packaging
daos-stack/pmdk-pkg pull request #26
Opened 2023-06-05 21:24 UTC by jolivier23

Need a new PMDK commit to make internal scan happy

2023-06-30 12:07 UTC, brianjmurrell requested changes
You have some duplicate file warnings in the rpmlinting:

```
libpmem-devel.x86_64: W: files-duplicate /usr/share/man/man3/pmem_errormsg.3.gz /usr/share/man/man3/pmem_check_version.3.gz
libpmem-devel.x86_64: W: files-duplicate /usr/share/man/man3/pmem_persist.3.gz /usr/share/man/man3/pmem_deep_drain.3.gz:/usr/share/man/man3/pmem_deep_flush.3.gz:/usr/share/man/man3/pmem_deep_persist.3.gz:/usr/share/man/man3/pmem_drain.3.gz:/usr/share/man/man3/pmem_has_auto_flush.3.gz:/usr/share/man/man3/pmem_has_hw_drain.3.gz:/usr/share/man/man3/pmem_msync.3.gz
libpmem-devel.x86_64: W: files-duplicate /usr/share/man/man3/pmem_unmap.3.gz /usr/share/man/man3/pmem_map_file.3.gz
libpmem-devel.x86_64: W: files-duplicate /usr/share/man/man3/pmem_memset_persist.3.gz /usr/share/man/man3/pmem_memcpy.3.gz:/usr/share/man/man3/pmem_memcpy_nodrain.3.gz:/usr/share/man/man3/pmem_memcpy_persist.3.gz:/usr/share/man/man3/pmem_memmove.3.gz:/usr/share/man/man3/pmem_memmove_nodrain.3.gz:/usr/share/man/man3/pmem_memset.3.gz:/usr/share/man/man3/pmem_memset_nodrain.3.gz
…
```

For some reason, only on EL*, https://github.com/daos-stack/pmdk/blob/f9ae80bd1a6707a518493982c0b301c690d5d035/pmdk.spec#L598 does not seem to be working.  Well, it is working:

```
+ _target=/builddir/build/BUILDROOT/pmdk-1.13.1-1.el7.x86_64//usr/share/man/man3/pmem_errormsg.3.gz
+ read _file
+ test -z /builddir/build/BUILDROOT/pmdk-1.13.1-1.el7.x86_64//usr/share/man/man3/pmem_errormsg.3.gz
+ test -z /builddir/build/BUILDROOT/pmdk-1.13.1-1.el7.x86_64//usr/share/man/man3/pmem_check_version.3.gz
+ test 0 = 1
+ ln -f /builddir/build/BUILDROOT/pmdk-1.13.1-1.el7.x86_64//usr/share/man/man3/pmem_errormsg.3.gz /builddir/build/BUILDROOT/pmdk-1.13.1-1.el7.x86_64//usr/share/man/man3/pmem_check_version.3.gz
```

But `rpmlint` still seems to complain about it.  Can you put a bit of debug after that line above to verify that the above linking actually happened?
```

2023-06-30 12:07 UTC, brianjmurrell commented on debian/changelog
> + -- Jeff Olivier <jeffrey.v.olivier@intel.com>  Tue, 06 Jun 2023 08:32:15 -0400
Could update the date here on the next push so that it's a bit more accurate.

2023-06-30 12:07 UTC, brianjmurrell commented on pmdk.spec
> +* Tue Jun 06 2023 Jeff Olivier <jeffrey.v.olivier@intel.com> - 1.13.1-1
Could update the date here on the next push so that it's a bit more accurate.

2023-06-30 12:14 UTC, brianjmurrell commented
Also, on your next push, can you add `el9` to the lsit of distros in the `Jenkinsfile`, P&T.  I guess due to EL9 having `pmdk` (but it's only 1.12.1) I missed this one in the EL9 updates.

2023-06-30 19:20 UTC, jolivier23 commented on debian/changelog
> + -- Jeff Olivier <jeffrey.v.olivier@intel.com>  Tue, 06 Jun 2023 08:32:15 -0400
Thanks, I may have to leave it to someone else to push this along since I'm OOO til July 31.  @janekmi would you be able to fix this issues here?

2023-06-30 19:21 UTC, jolivier23 commented
We basically own pmdk now so I'd say we should probably supply it ourselves.

2023-07-04 14:25 UTC, brianjmurrell commented
@janekmi 
>  janekmi force-pushed the jvolivie/pmdk branch 2 times, most recently from c60de76 to 3f38b75

FYI: We don't allow force-push once reviewing has started as it voids the reviewers' ability to incrementally review and requires they review the full patch repeatedly.

2023-07-13 20:58 UTC, janekmi commented
> @janekmi
> 
> > janekmi force-pushed the jvolivie/pmdk branch 2 times, most recently from [c60de76](https://github.com/daos-stack/pmdk/commit/c60de76a6955228a2e1c28c68c43049585266309) to [3f38b75](https://github.com/daos-stack/pmdk/commit/3f38b7587f4b218055d0ac86fe55af926188623c)
> 
> FYI: We don't allow force-push once reviewing has started as it voids the reviewers' ability to incrementally review and requires they review the full patch repeatedly.

Sorry. Didn't know that.

So, I will add further commits and eventually squash them before the merge, would it be alright?

2023-07-31 16:47 UTC, jolivier23 commented
> > @janekmi
> > > janekmi force-pushed the jvolivie/pmdk branch 2 times, most recently from [c60de76](https://github.com/daos-stack/pmdk/commit/c60de76a6955228a2e1c28c68c43049585266309) to [3f38b75](https://github.com/daos-stack/pmdk/commit/3f38b7587f4b218055d0ac86fe55af926188623c)
> > 
> > 
> > FYI: We don't allow force-push once reviewing has started as it voids the reviewers' ability to incrementally review and requires they review the full patch repeatedly.
> 
> Sorry. Didn't know that.
> 
> So, I will add further commits and eventually squash them before the merge, would it be alright?

yes, commits will get squashed by gatekeeper before merge

2023-09-06 15:34 UTC, brianjmurrell commented on pmdk.spec
> +* Tue Jul 04 2023 Jeff Olivier <jeffrey.v.olivier@intel.com> - 1.13.1
Let's update this date stamp if you need to push again please.

2023-09-06 15:34 UTC, brianjmurrell commented on debian/changelog
> + -- Jeff Olivier <jeffrey.v.olivier@intel.com>  Tue, 04 Jul 2023 08:32:15 -0400
Let's update this date stamp if you need to push again please.

2023-09-06 15:40 UTC, brianjmurrell requested changes
You need to make the pmreorder package a _noarch_ package to address the rpmlint error on Leap 15.  Not really sure why it's only tripping on that platform though.

https://fedoraproject.org/wiki/Common_Rpmlint_issues#no-binary

2023-09-07 12:20 UTC, janekmi commented
> You need to make the pmreorder package a _noarch_ package to address the rpmlint error on Leap 15. Not really sure why it's only tripping on that platform though.
> 
> https://fedoraproject.org/wiki/Common_Rpmlint_issues#no-binary

Thanks for the tip. :D Yeah. It is interesting. I will consider porting this fix to [pmem/pmdk](https://github.com/pmem/pmdk/blob/master/utils/pmdk.spec.in#L363).

**Note**: After consideration, I think this PR should be about fixing the PMDK's packaging only. I will bump up the PMDK version in a separate PR. Probably directly onto the 2.0 release.

2023-09-11 20:18 UTC, brianjmurrell requested changes

2023-09-11 20:18 UTC, brianjmurrell commented on pmdk.rpmlintrc
> +addFilter('W: files-duplicate /usr/share/man/man3/.*')
The generally accepted solution to this, so that it does not need an exception here is to [utilize the `%fdupes` macro](https://en.opensuse.org/openSUSE:Packaging_Conventions_RPM_Macros#%25fdupes) on the duplicated files.

2023-09-11 20:18 UTC, brianjmurrell commented on pmdk.spec
> +%global _hardened_build 2
This macro is not signifying the package `Release:`.  This is a boolean to enable a _hardened_ build.  It should be `1` (true) not `2`.

2023-09-11 20:18 UTC, brianjmurrell commented on pmdk.spec
> +Release:    %{_hardened_build}%{?dist}
```suggestion
Release:    2%{?dist}
```

2023-09-12 13:53 UTC, brianjmurrell requested changes
I'm not seeing any changes that address any of my previous comments.

2023-09-12 14:30 UTC, janekmi commented on pmdk.rpmlintrc
> +addFilter('W: files-duplicate /usr/share/man/man3/.*')
Following your suggestion, I attempted to fix this using the recommended command (`%fdupes -s %{buildroot}/%{_mandir}`) but locally it generated further warnings like this one:

```
libpmempool-devel.x86_64: W: dangling-relative-symlink /usr/share/man/man3/pmempool_feature_disable.3.gz //usr/share/man/man3/pmempool_feature_enable.3.gz
```

Hope it will miraculously just work on Jenkins. 🤞

2023-09-12 14:44 UTC, janekmi commented on pmdk.rpmlintrc
> +addFilter('W: files-duplicate /usr/share/man/man3/.*')
Sadly, this macro does not solve the issue. Jenkins reports a bunch of `dangling-relative-symlink` warnings as well. Do you have any experience in using this macro or any tips on how I might solve these warnings?

2023-09-12 14:57 UTC, janekmi commented on pmdk.rpmlintrc
> +addFilter('W: files-duplicate /usr/share/man/man3/.*')
Ok. I think I got it. It works locally now.

2023-09-12 15:31 UTC, brianjmurrell commented on debian/changelog
> + -- Jan Michalski <jan.michalski@intel.com>  Thu, 12 Sep 2023 13:00:00 +0000
```suggestion
 -- Jan Michalski <jan.michalski@intel.com>  Tue, 12 Sep 2023 13:00:00 +0000
```

2023-09-12 15:33 UTC, brianjmurrell commented on pmdk.spec
> +* Thu Sep 12 2023 Jan Michalski <jan.michalski@intel.com> - 1.12.1-2
```suggestion
* Tue Sep 12 2023 Jan Michalski <jan.michalski@intel.com> - 1.12.1-2
```

2023-09-12 15:34 UTC, brianjmurrell commented on pmdk.spec
> +%if 0%{?_skip_check} == 0
Is this temporary?  It seems to contradict the meaning and documentation of the flag

2023-09-12 15:39 UTC, janekmi commented on pmdk.spec
> +%if 0%{?_skip_check} == 0
Good catch. Just a debug change. Committed unintentionally.

2023-09-18 15:41 UTC, brianjmurrell commented on pmdk.spec
> +%if 0%{?_skip_check} == 0
@janekmi You should leave resolving conversations to the person who opened it so that they can verify the resolution to their comment meets their requirements and indicates so by resolving the conversation.

2023-09-18 15:45 UTC, brianjmurrell approved these changes

2023-09-18 18:42 UTC, merged