Update to 2.0
daos-stack/pmdk-pkg pull request #33
Opened 2023-09-19 06:51 UTC by janekmi

2023-09-19 11:41 UTC, brianjmurrell requested changes
Wouldn't you want to disable the exclusion of ndctl in this PR similar to what you are doing in #32?

2023-09-19 11:41 UTC, brianjmurrell commented on debian/changelog
> +  * Upgrade to 2.0.0
Please expand on the resulting packaging differences this release makes (i.e. the changes to `debian/control` and associated files) and why those are needed (i.e. the changes in pmdk-2.0.0 that are causing them).

2023-09-19 11:41 UTC, brianjmurrell commented on pmdk.spec
> +- Update to release 2.0.0
Please expand on the resulting packaging differences this release makes (i.e. the changes to the subpackages) and why those are needed (i.e. the changes in pmdk-2.0.0 that are causing them).

2023-09-19 17:33 UTC, grom72 commented
> Wouldn't you want to disable the exclusion of ndctl in this PR similar to what you are doing in #32?

@brianjmurrell as I see from the initial builds of #32, it will be easier to update first to 2.0.0 and then to enable back the ndctl.

2023-09-20 07:58 UTC, janekmi commented on debian/changelog
> +  * Upgrade to 2.0.0
Done.

2023-09-20 07:58 UTC, janekmi commented on pmdk.spec
> +- Update to release 2.0.0
Done.

2023-09-20 08:01 UTC, janekmi commented
> > Wouldn't you want to disable the exclusion of ndctl in this PR similar to what you are doing in #32?
> 
> @brianjmurrell as I see from the initial builds of #32, it will be easier to update first to 2.0.0 and then to enable back the ndctl.

Agreed. Moreover, the update to 2.0 should be relatively easy whereas reinstantiating the NDCTL use has already proven to be challenging. On top of that, I think doing two big changes at once is too risky. :wink:

2023-09-20 13:38 UTC, grom72 requested changes

2023-09-20 13:38 UTC, grom72 commented on pmdk.spec
%define min_ndctl_ver 63.1

BuildRequires:  glibc-devel - not mentioned or used by PMDK
BuildRequires:  autoconf - only needed for valgrind
BuildRequires:  automaker -  --//--
BuildRequires:  gdb - is it required here?
BuildRequires: man -  -- // --

2023-09-21 11:09 UTC, janekmi commented on pmdk.spec
It seems all of these were redundant:
- glibc-devel
- autoconf
- automake
- gdb

But `man` is required since it provides `lexgrog` that is used here: https://github.com/pmem/pmdk/blob/069efd7e26bbefde1f75c87ffc477c1c001c7984/utils/check-manpage#L52.

2023-09-21 14:16 UTC, grom72 approved these changes

2023-09-21 14:38 UTC, grom72 submitted a review, later dismissed

2023-09-25 13:22 UTC, brianjmurrell requested changes

2023-09-25 13:22 UTC, brianjmurrell commented on pmdk.spec
> -BuildRequires:  automake
Are these no longer needed to build pmdk?  Did 2.0.0 change configure/build systems?  https://github.com/pmem/pmdk/blob/ba92d6b469d52d16f26279bebaf317bbdbb3822c/INSTALL.md?plain=1#L12-L14 seems to indicate that `autoconf` is still used.

As for glibc-devel, does pmdk really not use glibc at all?

2023-09-25 13:22 UTC, brianjmurrell commented on pmdk.spec
> +    BUILD_BENCHMARKS=n
Given that these are common and being repeated 3 times (and as you can see, having to be updated in 3 different places) it might be good to have these defined in a macro once and then referenced in the 3 places they are needed.  Then any future updates of these will only be in the one place.

2023-09-25 13:22 UTC, brianjmurrell commented on pmdk.spec
> +- Remove deprecated build requirements.
Is this the removal of the `autoconf` (and friends) `BuildRequires:`?  It's not clear to me that this should be done.  Pending your answer on the previous question.

2023-09-26 11:24 UTC, janekmi commented on pmdk.spec
> -BuildRequires:  automake
Removing `glibc-devel` is one step too far. 😁 

But `autoconf` and `automake` are not used. Sadly, `INSTALL.md` requires cleanup.

2023-09-26 11:24 UTC, janekmi commented on pmdk.spec
> +- Remove deprecated build requirements.
Yes. This is this little cleanup in `BuildRequires`. To be clear I just added the list of removed dependencies.

2023-09-26 11:24 UTC, janekmi commented on pmdk.spec
> +    BUILD_BENCHMARKS=n
Done.

2023-09-26 12:49 UTC, brianjmurrell commented on pmdk.spec
>  %endif
This could be processed as part of `make_common_args` to further DRY this out.

2023-09-26 12:52 UTC, brianjmurrell commented
What is the intention of #32 in relation to this PR?

2023-09-26 14:44 UTC, janekmi commented on pmdk.spec
>  %endif
Done.

2023-09-26 14:56 UTC, janekmi commented
> What is the intention of #32 in relation to this PR?

This PR is about bumping up the PMDK version to the latest 2.0 release. #32 attempts to restore usage of NDCTL which is critical for PMDK to assure correctness of data read from PMem.

Both of these are required and orthogonal. #32 has to happen in some form no matter whether we decide to upgrade PMDK or not. Upgrading PMDK is not required to re-enable NDCTL. I think why we need to upgrade PMDK is self-explanatory and unrelated to the NDCTL issue.

I do not foresee technical difficulties in landing this PR. Whereas #32 requires solving some technical difficulties as you may recall from [DAOS-4183](https://daosio.atlassian.net/browse/DAOS-4183).

2023-09-26 17:10 UTC, brianjmurrell commented
> I do not foresee technical difficulties in landing this PR. Whereas #32 requires solving some technical difficulties as you may recall from [DAOS-4183](https://daosio.atlassian.net/browse/DAOS-4183).

But really, if you land this one before #32, you will need to rebase #32 on master again to pick this one up, yes?

If #32 is intended to land first though, should the `BuildRequires:` you removed here be removed there also?  Perhaps there is duplicate make args that can be consolidated as you have done here also?

2023-09-26 17:11 UTC, brianjmurrell commented on pmdk.spec
> +%endif
So much nicer the `%build` and `%check` scriptlets look with this!

2023-09-26 17:20 UTC, brianjmurrell commented
Seems to be [failing testing](https://jenkins-1.wolf.hpdd.intel.com:9090/blue/organizations/jenkins/daos-stack%2Fdaos/detail/ci-daos-stack-pmdk-PR-33-master/5/tests) though still.  Is this expected?

2023-09-26 20:58 UTC, janekmi commented on pmdk.spec
> +%endif
They are indeed. 😄 Thanks for the suggestion!

2023-09-26 21:05 UTC, janekmi commented
> But really, if you land this one before #32, you will need to rebase #32 on master again to pick this one up, yes?

It is true. But I bet @grom72 doesn't mind. Probably #32 should be marked as a draft just not to bother you before it is even ready to be reviewed, am I right @grom72? And this is probably where the confusion comes from. I am not sure what the practice is in this case.

> If #32 is intended to land first though, ...

It is highly improbable. #32 requires first fixes to daos-stack/daos which are far from being ready.

2023-09-28 07:45 UTC, janekmi commented
> Seems to be [failing testing](https://jenkins-1.wolf.hpdd.intel.com:9090/blue/organizations/jenkins/daos-stack%2Fdaos/detail/ci-daos-stack-pmdk-PR-33-master/5/tests) though still. Is this expected?

A funny thing. The [latest build](https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fpmdk/detail/PR-33/11/pipeline) combined with [this replay](https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/ci-daos-stack-pmdk-PR-33-master/10/pipeline/481/) constitutes one successful run. @brianjmurrell is it okay or I should further investigate?

2023-10-02 14:01 UTC, brianjmurrell approved these changes

2023-10-02 14:03 UTC, brianjmurrell commented
Please add @daos-stack/release-engineering as a reviewer if/when you are ready to land this and have this version of PMDK be what is used on `master`, `release/2.4` and `release/2.2`.

2023-10-02 15:38 UTC, grom72 approved these changes

2023-10-03 17:53 UTC, merged