DAOS-14514 pmdk: update to version 2.0.1
daos-stack/pmdk-pkg pull request #35
Opened 2023-12-12 10:08 UTC by grom72

Upgrade to version 2.0.1.
This is the version that allows enabling NDCTL without risk of stack over-usage in argobots ULT.

Obsolete libraries lbpmemblk and libpmemlog has been removed.

2023-12-12 12:45 UTC, janekmi submitted a review, later dismissed

2023-12-12 13:11 UTC, osalyk submitted a review, later dismissed

2023-12-12 13:38 UTC, brianjmurrell approved these changes

2023-12-12 13:49 UTC, brianjmurrell requested changes
Do we want this built with or without `ndctl` at this point in time?  Currently it's still being built without:

```
+ make -j72 EXTRA_CFLAGS=-Wno-error NORPATH=1 BUILD_EXAMPLES=n BUILD_BENCHMARKS=n NDCTL_ENABLE=n
```
If you want to change this default behaviour you need to change
https://github.com/daos-stack/pmdk/blob/40f6fc0885019ae04d33863967f9db7f5490bd4a/pmdk.spec#L27 to
```
 %bcond_with ndctl
```

That option would then match what the comment above it says.

If you do not want to build with `ndctl` by default (i.e. the status quo), you can leave the above line as is, but please update the comment to reflect that the default is to build **without** it.  That comment has been wrong ever since the beginning, unfortunately.

Since you need to push an update anyway, it would be good to update the date/timestamps in the `debian/changelog` and `daos.spec` `%changelog` also.

2023-12-14 22:04 UTC, JohnMalmberg submitted a review, later dismissed

2024-01-08 17:06 UTC, brianjmurrell requested changes
Testing on both daos [`master`](https://jenkins-1.wolf.hpdd.intel.com:9090/blue/organizations/jenkins/daos-stack%2Fdaos/detail/ci-daos-stack-pmdk-PR-35-master/11/tests) and [`release/2.4`](https://jenkins-1.wolf.hpdd.intel.com:9090/blue/organizations/jenkins/daos-stack%2Fdaos/detail/ci-daos-stack-pmdk-PR-35-release-2.4/11/tests) are quite the bloodbaths.  Surely all of those failures are not unrelated, are they?

Just going to -1 until we get to the bottom of that massive amount of failure.

2024-01-08 17:06 UTC, brianjmurrell commented on Makefile
> +EXTERNAL_RPM_BUILD_OPTIONS := --with=ndctl
This is the default now, with the change to https://github.com/daos-stack/pmdk/blob/grom72/pmdk-2.0.1/pmdk.spec#L27, yes?  If so, we can get rid of this line entirely since the default behaviour is what we want.

2024-01-08 17:06 UTC, brianjmurrell commented on debian/changelog
> + -- Tomasz Gromadzki <tomasz.gromadzki@intel.com>  Tue, 12 Dec 2023 13:00:00 +0000
Let's update this timestamp if any further pushes are required.

2024-01-08 17:06 UTC, brianjmurrell commented on pmdk.spec
> +* Tue Dec 12 2023  Tomasz.Gromadzki <tomasz.gromadzki@intel.com> - 2.0.1-1
Let's update this timestamp if any further pushes are required.

2024-01-11 12:01 UTC, grom72 commented on Makefile
> +EXTERNAL_RPM_BUILD_OPTIONS := --with=ndctl
Done

2024-01-11 12:01 UTC, grom72 commented on debian/changelog
> + -- Tomasz Gromadzki <tomasz.gromadzki@intel.com>  Tue, 12 Dec 2023 13:00:00 +0000
Done

2024-01-11 12:01 UTC, grom72 commented on pmdk.spec
> +* Tue Dec 12 2023  Tomasz.Gromadzki <tomasz.gromadzki@intel.com> - 2.0.1-1
Done

2024-01-15 18:09 UTC, brianjmurrell commented on pmdk.spec
> +* Tue Dec 12 2023  Tomasz.Gromadzki <tomasz.gromadzki@intel.com> - 2.0.1-1
I'm going to assume that with these changes this is ready for review again.  Generally speaking once you are finished with updating your PR with review fixes, you should click the re-review button next to any reviewers you wish to take another look at the PR:

![image](https://github.com/daos-stack/pmdk/assets/559317/cd5ef61e-682e-444b-b145-e299f9080f5d)

so that they know you are done making changes and that you are wanting a new round of reviews.  Otherwise those folks will continue to wait until they are re-requested and you will be waiting for them while they wait for you.

2024-01-15 18:25 UTC, brianjmurrell commented on pmdk.spec
> +%bcond_with ndctl
I checked the actual build and it seems it's still building without _ndctl_:

```
+ make EXTRA_CFLAGS=-Wno-error NORPATH=1 BUILD_EXAMPLES=n BUILD_BENCHMARKS=n NDCTL_ENABLE=n check
```

Upon [re-reading about `%bcond_with[out]`](https://rpm-software-management.github.io/rpm/manual/conditionalbuilds.html), as confusing at it seems we want to use:

```suggestion
%bcond_without ndctl
```

That does make sense when you consider the hint that the explanation in the URL above:
> These macros create command line options.

So what we are trying to do here is create a `--without-ndctl` `rpmbuild` option to disable the default behaviour of building with _ndctl_.

Apologies for any previous mis-direction I may have given in this regard.

2024-01-15 18:25 UTC, brianjmurrell requested changes
It would be nice to have a test in daos' ftest subdir that tests and confirms the behaviour that having _ndctl_ enabled provides.  This will mitigate any future regressions in regard to this functionality being enabled and working.

That said, we do appear to have test failures in the downstream testing:
[master](https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/ci-daos-stack-pmdk-PR-35-master/15/tests)
[release/2.4](https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/ci-daos-stack-pmdk-PR-35-release-2.4/15/tests)

Do we know that these are unrelated to this update?

2024-01-18 23:27 UTC, grom72 commented on pmdk.spec
> +* Tue Dec 12 2023  Tomasz.Gromadzki <tomasz.gromadzki@intel.com> - 2.0.1-1
Done

2024-01-18 23:27 UTC, grom72 commented on pmdk.spec
> +%bcond_with ndctl
Done

2024-01-18 23:33 UTC, grom72 commented
> It would be nice to have a test in daos' ftest subdir that tests and confirms the behaviour that having _ndctl_ enabled provides. This will mitigate any future regressions in regard to this functionality being enabled and working.
> 
We can add such a test as soon as we enable logging in to the next version of PMDK (2.1.0).
Currently, there is no easy way to check this (at least in the release version).

> That said, we do appear to have test failures in the downstream testing: [master](https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/ci-daos-stack-pmdk-PR-35-master/15/tests) [release/2.4](https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/ci-daos-stack-pmdk-PR-35-release-2.4/15/tests)
> 
> Do we know that these are unrelated to this update?
Failed tests on the `master` are related to MDonSSD where PMem (and ndctl) shall not be used at all.

`release-2.4` most probably can be ignored as there is no plan to release 2.4.x with NDCTL enabled.

2024-01-22 16:51 UTC, brianjmurrell commented
> We can add such a test as soon as we enable logging in to the next version of PMDK (2.1.0). Currently, there is no easy way to check this (at least in the release version).

Can you keep this in mind for a future update of this package?

> Failed tests on the `master` are related to MDonSSD where PMem (and ndctl) shall not be used at all.

Looking at the failure results [here](https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/ci-daos-stack-pmdk-PR-35-master/17/tests) it would seem that only a minor number of failures on _on SSD_ and that the lion's share of failures are on the regular _Functional Hardware Medium_ stage.  Quite a number of failures there, indeed.

If we look at the master commit that that downstream testing is based on, [91b93c8](https://github.com/daos-stack/daos/tree/91b93c84e8159b275baa42b0a4507229bb3a91a6) and look at it's testing results, there are no hardware testing results due to it being a landing, however if we look at the [daily-testing from the same time period (where hardware stages are run)](https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/daily-testing/49/tests) we can see there are quite a bit fewer failures.  So we need to understand why there are so many failures in the downstream testing here and if they are known or explainable outside of the changes being made here.

> `release-2.4` most probably can be ignored as there is no plan to release 2.4.x with NDCTL enabled.

It's not that simple.  Any future 2.4.x release will include a PMDK with this PR landed to it.  This is why we run downstream testing for all current release branches when we test PRs of dependencies.

Fortunately the failures here are much smaller.  Only a single test in fact that just failed on multiple distros.

That only a single test failed on 2.4 is a good sign, but why so many failures on master?

2024-05-09 12:30 UTC, osalyk approved these changes, later dismissed

2024-05-13 15:06 UTC, brianjmurrell commented on Jenkinsfile
> +				 'test-tag': 'pr'])
@jolivier23 You had set this test tag to `daosio` back in 336f35f.  Does it seem reasonable to change that to the more limited `pr` test set at this point?

2024-05-13 15:13 UTC, brianjmurrell commented on Makefile
> +EXTERNAL_RPM_BUILD_OPTIONS := --without=ndctl
I'm not sure I agree with using this mechanism.

The problem it creates is that if somebody just picks up the SRPM or even just the `.spec` file for this package and builds it without knowing that our build is using this switch, they get a different result from what we are getting.

Don't get me wrong.  I think having switches in the specfile can be useful, but I think we need to always ensure that the result of building without any switches is the result that we want people to get by default.  Beyond that, they can use whatever switches they want to intentionally get a different result from our default.

2024-06-11 07:13 UTC, grom72 commented
Skipping 2.0.1. 
Jumping directly to the new version 2.1.0 with #37

2024-06-11 07:13 UTC, closed without merging