PMDK release 2.1.0 w/o NDCTL enabled
daos-stack/pmdk-pkg pull request #37
Opened 2024-05-13 12:02 UTC by grom72

2024-05-13 12:48 UTC, brianjmurrell commented on debian/changelog
> +* Fri May 10 2024  Tomasz.Gromadzki <tomasz.gromadzki@intel.com> * 2.1.0-1
```suggestion
pmdk (2.1.0-1) stable; urgency=medium
```

2024-05-13 12:51 UTC, brianjmurrell commented on pmdk.spec
> +    %define make_common_args %{_make_common_args} NDCTL_ENABLE=n PMEMOBJ_IGNORE_DIRTY_SHUTDOWN=y PMEMOBJ_IGNORE_BAD_BLOCKS=y
I'm assuming `PMEMOBJ_IGNORE_DIRTY_SHUTDOWN=y PMEMOBJ_IGNORE_BAD_BLOCKS=y` only apply when `NDCTL_ENABLE=n`, yes?

2024-05-13 12:56 UTC, brianjmurrell commented on pmdk.spec
> +- This version is build w/o NDCTL support
But https://github.com/daos-stack/pmdk/blob/efb8e66c329ba8a52c1ba7270d2c9a921576ec53/pmdk.spec#L27 means this actually is built with NDCTL doesn't it?  I.e. that line adds the `--without ndctl` option which means that https://github.com/daos-stack/pmdk/blob/efb8e66c329ba8a52c1ba7270d2c9a921576ec53/pmdk.spec#L27 does not get used unless the `--without ndctl` option is actually used which should not get used for our builds.

2024-05-13 12:58 UTC, grom72 commented on debian/changelog
> +* Fri May 10 2024  Tomasz.Gromadzki <tomasz.gromadzki@intel.com> * 2.1.0-1
Done

2024-05-13 12:59 UTC, brianjmurrell commented on debian/changelog
> +pmdk (2.0.1-1) stable; urgency=medium
The _version-release_ in this entry is seems to be a duplicate of the entry above it.

2024-05-13 12:59 UTC, grom72 commented on pmdk.spec
> +- This version is build w/o NDCTL support
It is done in `Makefile`:
`EXTERNAL_RPM_BUILD_OPTIONS := --without=ndctl`

2024-05-13 12:59 UTC, brianjmurrell commented on debian/rules
> +BUILD_ARGS = prefix=/usr libdir=/usr/lib/$(DEB_HOST_MULTIARCH) sysconfdir=/etc bashcompdir=/usr/share/bash-completion/completions NORPATH=1 BUILD_EXAMPLES=n BUILD_BENCHMARKS=n
Removing `NDCTL_ENABLE=n` here seems to be in conflict with https://github.com/daos-stack/pmdk/blob/108170d89730bd4352e2bdfae3c0d4a9e1db2d5a/debian/changelog#L21.

2024-05-13 18:10 UTC, grom72 commented on pmdk.spec
> +    %define make_common_args %{_make_common_args} NDCTL_ENABLE=n PMEMOBJ_IGNORE_DIRTY_SHUTDOWN=y PMEMOBJ_IGNORE_BAD_BLOCKS=y
Yes, as an additional protection mechanism.

2024-05-13 18:10 UTC, grom72 commented on debian/changelog
> +pmdk (2.0.1-1) stable; urgency=medium
Fixed

2024-05-15 10:35 UTC, grom72 commented on debian/rules
> +BUILD_ARGS = prefix=/usr libdir=/usr/lib/$(DEB_HOST_MULTIARCH) sysconfdir=/etc bashcompdir=/usr/share/bash-completion/completions NORPATH=1 BUILD_EXAMPLES=n BUILD_BENCHMARKS=n
Fixed

2024-05-24 10:38 UTC, janekmi commented on pmdk.spec
> +  Update to release 2.1.0 w/o NDCTL support which:
Nitpick but not having a dash here is unprecedented for this file. I would recommend either adding it back or starting from the beginning of the line. Having two empty spaces at the beginning of the line just takes the worst from both solutions.

Note: Starting from the beginning of the line also means you probably should the list below unindent so all the dashes will be at the beginning of the respective lines.

```suggestion
- Update to release 2.1.0 w/o NDCTL support which:
```

2024-05-24 10:38 UTC, janekmi commented on pmdk.spec
> +  Includes also release 2.0.1 which
The same as above.
```suggestion
  Includes also release 2.0.1 which
```

2024-05-24 10:38 UTC, janekmi commented on debian/changelog
> +    * Drops support for building without libpthread (NO_LIBPTHREAD build-time define).* Reduces libpmemobj's stack usage below the 11kB threshold,
```suggestion
    * Drops support for building without libpthread (NO_LIBPTHREAD build-time define).
```

2024-05-24 10:57 UTC, grom72 commented on pmdk.spec
> +  Update to release 2.1.0 w/o NDCTL support which:
Done

2024-05-24 10:58 UTC, grom72 commented on debian/changelog
> +    * Drops support for building without libpthread (NO_LIBPTHREAD build-time define).* Reduces libpmemobj's stack usage below the 11kB threshold,
Done

2024-05-24 14:30 UTC, janekmi commented on debian/changelog
> +    * Reduces libpmemobj's stack usage below the 11kB threshold,
Duplicate.

```suggestion
```

2024-05-24 14:59 UTC, grom72 commented on debian/changelog
> +    * Reduces libpmemobj's stack usage below the 11kB threshold,
Done

2024-05-27 10:03 UTC, janekmi approved these changes, later dismissed

2024-07-08 08:25 UTC, janekmi commented
The last build test results:

- Skip-list:
  - test_daos_rebuild_ec:DAOS-14982
- Skip-list-master:
  - DaosCoreTest:DAOS-16008
  - test_daos_container:DAOS-16021 (resolved)
  - test_osa_offline_reintegration_without_checksum:DAOS-15608
- master:
  - test_ms_failover:DAOS-16103 (resolved)
- release/2.6:
  - test_daos_rebuild_simple:DAOS-15290
  - test_daos_pool:DAOS-16084
  - test_daos_container:DAOS-16083
  - test_daos_pipeline:DAOS-16085 (resolved)
  - test_osa_offline_reintegration_without_checksum:DAOS-15608
  - test_daos_pipeline:DAOS-16085 (resolved)
  - test_daos_dfs_unit:DAOS-16087 (resolved)
  
Updated skip lists:
  
```
Skip-list: test_daos_rebuild_ec:DAOS-14982
Skip-list-master: DaosCoreTest:DAOS-16008 test_osa_offline_reintegration_without_checksum:DAOS-15608
Skip-list-release/2.6: test_daos_rebuild_simple:DAOS-15290 test_daos_pool:DAOS-16084 test_daos_container:DAOS-16083 test_osa_offline_reintegration_without_checksum:DAOS-15608
```

2024-07-08 15:04 UTC, janekmi commented
- Skip-list:
  - test_daos_rebuild_ec:DAOS-14982
- Skip-list-master:
  - DaosCoreTest:DAOS-16008
  - test_osa_offline_reintegration_without_checksum:DAOS-15608
- Skip-list-release/2.6:
  - test_daos_rebuild_simple:DAOS-15290
  - test_daos_pool:DAOS-16084 (resolved)
  - test_daos_container:DAOS-16083
  - test_osa_offline_reintegration_without_checksum:DAOS-15608
- master:
  - test_dfuse_daos_build_wt_il:DAOS-16168
- release/2.6:
  - test_dfuse_daos_build_wt_il:DAOS-16168
  
Updated skip lists:
  
```
Skip-list: test_daos_rebuild_ec:DAOS-14982
Skip-list-master: DaosCoreTest:DAOS-16008 test_osa_offline_reintegration_without_checksum:DAOS-15608 test_dfuse_daos_build_wt_il:DAOS-16168
Skip-list-release/2.6: test_daos_rebuild_simple:DAOS-15290 test_daos_container:DAOS-16083 test_osa_offline_reintegration_without_checksum:DAOS-15608 

```

2024-07-09 09:43 UTC, janekmi commented
- Skip-list:
  - test_daos_rebuild_ec:DAOS-14982
  - test_dfuse_daos_build_wt_il:DAOS-16168 (resolved on master)
- Skip-list-master:
  - DaosCoreTest:DAOS-16008
  - test_osa_offline_reintegration_without_checksum:DAOS-15608
- Skip-list-release/2.6:
  - test_daos_rebuild_simple:DAOS-15290
  - test_daos_container:DAOS-16083
  - test_osa_offline_reintegration_without_checksum:DAOS-15608

- master:
  - test_dfuse_daos_build_wt_pil4dfs:DAOS-16168 (resolved)
- release/2.6:
  - test_dfuse_daos_build_wt_pil4dfs:DAOS-16168

Updated skip lists:

```
Skip-list: test_daos_rebuild_ec:DAOS-14982
Skip-list-master: DaosCoreTest:DAOS-16008 test_osa_offline_reintegration_without_checksum:DAOS-15608
Skip-list-release/2.6: test_daos_rebuild_simple:DAOS-15290 test_daos_container:DAOS-16083 test_osa_offline_reintegration_without_checksum:DAOS-15608 test_dfuse_daos_build_wt_il:DAOS-16168 test_dfuse_daos_build_wt_pil4dfs:DAOS-16168

```

2024-07-11 09:39 UTC, janekmi commented
- Skip-list:
  - test_daos_rebuild_ec:DAOS-14982
- Skip-list-master:
  - DaosCoreTest:DAOS-16008
  - test_osa_offline_reintegration_without_checksum:DAOS-15608
- Skip-list-release/2.6:
  - test_daos_rebuild_simple:DAOS-15290
  - test_daos_container:DAOS-16083 (resolved)
  - test_osa_offline_reintegration_without_checksum:DAOS-15608
  - test_dfuse_daos_build_wt_il:DAOS-16168
  - test_dfuse_daos_build_wt_pil4dfs:DAOS-16168

- master:
  - test_dfuse_daos_build_wt_il:DAOS-16168
  - test_dfuse_daos_build_wt_pil4dfs:DAOS-16168
- release/2.6:
  - Suffered from SRE-2246.

2024-07-12 13:03 UTC, janekmi commented
- Skip-list:
  - test_daos_rebuild_ec:DAOS-14982
  - test_dfuse_daos_build_wt_il:DAOS-16168
  - test_dfuse_daos_build_wt_pil4dfs:DAOS-16168 -> DAOS-16215
  - test_osa_offline_reintegration_without_checksum:DAOS-15608
- Skip-list-master:
  - DaosCoreTest:DAOS-16008
- Skip-list-release/2.6:
  - test_daos_rebuild_simple:DAOS-15290

- master:
  - test_ms_failover:DAOS-16103
- release/2.6:
  - test_dfuse_daos_build_wb:DAOS-16215
  - test_dfuse_daos_build_wt:DAOS-16215
  - test_dfuse_daos_build_metadata:DAOS-16215
  - test_dfuse_daos_build_data:DAOS-16215
  - test_dfuse_daos_build_nocache:DAOS-16215
  - test_daos_rebuild_ec:DAOS-14982

2024-07-16 17:26 UTC, janekmi commented
Skip-list:
  - test_daos_rebuild_ec:DAOS-14982
  - test_dfuse_daos_build_wt_il:DAOS-16168 (resolved)
  - test_dfuse_daos_build_wt_pil4dfs:DAOS-16215
  - test_osa_offline_reintegration_without_checksum:DAOS-15608
Skip-list-master:
  - DaosCoreTest:DAOS-16008
  - test_ms_failover:DAOS-16103
Skip-list-release/2.6:
  - test_daos_rebuild_simple:DAOS-15290
  - test_dfuse_daos_build_wb:DAOS-16215
  - test_dfuse_daos_build_wt:DAOS-16215
  - test_dfuse_daos_build_metadata:DAOS-16215
  - test_dfuse_daos_build_data:DAOS-16215
  - test_dfuse_daos_build_nocache:DAOS-16215

Updated skip lists:
```
Skip-list: test_daos_rebuild_ec:DAOS-14982 test_dfuse_daos_build_wt_pil4dfs:DAOS-16215 test_osa_offline_reintegration_without_checksum:DAOS-15608
Skip-list-master: DaosCoreTest:DAOS-16008 test_ms_failover:DAOS-16103
Skip-list-release/2.6: test_daos_rebuild_simple:DAOS-15290 test_dfuse_daos_build_wb:DAOS-16215 test_dfuse_daos_build_wt:DAOS-16215 test_dfuse_daos_build_metadata:DAOS-16215 test_dfuse_daos_build_data:DAOS-16215 test_dfuse_daos_build_nocache:DAOS-16215

```

2024-07-18 14:52 UTC, janekmi commented
- Skip-list:
  - test_daos_rebuild_ec:DAOS-14982
  - test_dfuse_daos_build_wt_pil4dfs:DAOS-16215
  - test_osa_offline_reintegration_without_checksum:DAOS-15608
- Skip-list-master:
  - DaosCoreTest:DAOS-16008
  - test_ms_failover:DAOS-16103
- Skip-list-release/2.6:
  - test_daos_rebuild_simple:DAOS-15290
  - test_dfuse_daos_build_wb:DAOS-16215
  - test_dfuse_daos_build_wt:DAOS-16215
  - test_dfuse_daos_build_metadata:DAOS-16215
  - test_dfuse_daos_build_data:DAOS-16215
  - test_dfuse_daos_build_nocache:DAOS-16215

- master:
  - DaosCoreTest:DAOS-16008 (28 failures)
- release/2.6:
  - test_dfuse_daos_build_wt_il:DAOS-16168 (3 failures, reopen?)

2024-07-18 15:43 UTC, janekmi commented
@brianjmurrell it seems virtually impossible to catch up with the current state of DAOS and get a green build even with a quite extensive skip list. I cross-referenced all the failures with the relevant tickets so we have reasonable certainty the change in question did not cause them.

Additionally, considering the landing build does not include the "Test Hardware" stage which is the sole source of failures for all the Jenkins builds for this PR, there is a reasonable hope the landing build for this change will be successful despite the PR build is not.

So, hereby I ask this change to be landed just after the DAOS 2.6 GA. 🙏

2024-07-29 15:50 UTC, brianjmurrell commented
> Additionally, considering the landing build does not include the "Test Hardware" stage which is the sole source of failures for all the Jenkins builds for this PR, there is a reasonable hope the landing build for this change will be successful despite the PR build is not.

The downstream test builds of dependencies always include the same stages, even on landing, unlike the landing runs of daos itself.  This is because even ideally, daos landings would include hardware testing but due to their frequency, we just don't have the capacity to do that.  Dependency landings are much less frequent so we can still afford to do the hardware testing there and trying to skip it is simply not worth the extra logic contortion to do it (and maintain it).

But yes, I suppose we are just going to have to cave and force-land broken PRs due to the testing of daos being so unstable.  Unfortunately.

Please add @daos-stack/release-engineering to the reviewer list when you are ready for this to land.

2024-07-30 17:58 UTC, brianjmurrell requested changes

2024-07-30 17:58 UTC, brianjmurrell commented on pmdk.spec
> +%define _unpackaged_files_terminate_build 0
This is a recipe for accidentally not packaging files in the future.  It's better to explicitly remove any files you don't want packaged from the `%{buildroot}` in `%{install}`.  That additionally adds self-documentation to the fact that there are files that are normally in the _buildroot_ that we are intentionally not packaging.  A comment as to why would be additionally helpful.

2024-07-30 17:58 UTC, brianjmurrell commented on pmdk.spec
> +* Fri May 24 2024  Tomasz.Gromadzki <tomasz.gromadzki@intel.com> - 2.1.0-1
Please update the date here on your next push so that it's more recent/accurate.

2024-07-30 17:58 UTC, brianjmurrell commented on debian/changelog
> + -- Tomasz Gromadzki <tomasz.gromadzki@intel.com>  Fri, 24 May 2024 10:00:00 +0000
Please update the date/time here on your next push so that it's more recent/accurate.

2024-08-06 12:01 UTC, grom72 commented on pmdk.spec
> +* Fri May 24 2024  Tomasz.Gromadzki <tomasz.gromadzki@intel.com> - 2.1.0-1
Done

2024-08-06 12:04 UTC, grom72 commented on pmdk.spec
> +%define _unpackaged_files_terminate_build 0
Done
Please see `%{install}`.

2024-08-06 12:34 UTC, brianjmurrell commented on pmdk.spec
> +find %{buildroot} -name "libpmem2*" -type f -exec rm -f {} \;
FWIW, it's much more efficient to do: 

```suggestion
find %{buildroot} -name "libpmem2*" -type f -print0 | xargs -r0 rm -f
```
As it greatly reduces the number of `rm -f` commands executed.

But ultimately that `find` does not seem to be working per the latest run.

Can you remind me why we are trying to exclude pmem2 from the RPM?

Would it be better to have a build option that skips pmem2 in such a case?

2024-08-06 14:33 UTC, brianjmurrell commented
You need to update `packaging/` on one of your next commits:

![image](https://github.com/user-attachments/assets/c2ea69df-3bc4-4630-b0ab-5baceb3aacbc)

It's actually probably time to make that fail dependency pipelines now.

2024-08-06 15:28 UTC, grom72 commented on debian/changelog
> + -- Tomasz Gromadzki <tomasz.gromadzki@intel.com>  Fri, 24 May 2024 10:00:00 +0000
Done

2024-08-06 15:33 UTC, grom72 commented on pmdk.spec
> +%define _unpackaged_files_terminate_build 0
Not done - we will add an option to exclude libpmem2 from the PMDK build process with its release 2.1.1

2024-08-06 15:33 UTC, grom72 commented on pmdk.spec
> +find %{buildroot} -name "libpmem2*" -type f -exec rm -f {} \;
Let's make this change on the PMDK side with a new flag (this will be included in 2.1.1 release).

`libpmem2` library is not used at all by DAOS.

2024-08-07 13:37 UTC, brianjmurrell approved these changes

2024-08-08 10:41 UTC, janekmi approved these changes

2024-08-08 15:48 UTC, grom72 commented
These are the best results that we can achieve with our CI in terms of stable (but not green) test results
https://build.hpdd.intel.com/job/daos-stack/job/pmdk/job/PR-37/60/
https://build.hpdd.intel.com/job/daos-stack/job/daos/job/ci-daos-stack-pmdk-PR-37-master/44/testReport/
https://build.hpdd.intel.com/job/daos-stack/job/daos/job/ci-daos-stack-pmdk-PR-37-release-2.6/32/testReport/

We shall consider that the master branch's failures are related to the MD on SSD, where PMem (end PMDK) shall not be utilized at all.

It looks like PMDK does not introduce any problem that is permanent. New test failures appear and disappear in harmony with the rest of the project work. 

Therefore, I hereby support @janekmi 's request for this change to be accepted. 🙏

2024-08-14 16:59 UTC, brianjmurrell commented
> We shall consider that the master branch's failures are related to the MD on SSD, where PMem (end PMDK) shall not be utilized at all.

It's a shame we are even wasting cluster resources testing PMDK with MD-on-SSD.  But I talked to @phender and there is no existing mechanism to prevent that.  We *could* add some code to pipeline-lib for dependency jobs to specify downstream testing stages to include/exclude so that we can enable skipping of MD-on-SSD for pmdk for example.  Perhaps there are other situations that could benefit from this.

It would be good to open an SRE ticket to capture this new requirement.

2024-08-14 17:05 UTC, merged