WIP - enabling NDCTL on the top of pmdk 2.1.0
daos-stack/pmdk-pkg pull request #38
Opened 2024-05-16 07:23 UTC by grom72

This is a WIP branch to enable ndctl in DAOS.

2024-09-03 18:29 UTC, brianjmurrell requested changes
Not sure if this was ready for review or not, but since it's not a Draft, I have provided some suggestions.

2024-09-03 18:29 UTC, brianjmurrell commented on pmdk.spec
> -%bcond_with ndctl
Is there any use-case for `--without-ndctl`?

2024-09-03 18:29 UTC, brianjmurrell commented on pmdk.spec
> +%define make_common_args %{_make_common_args}
If there is no use-case for `--without-ndctl` then this indirection through `%{_make_common_args}` is no longer necessary and just adds confusion (this suggestion may look goofy because GH doesn't really support suggesting on non-changed lines, but I suspect you will get the meaning regardless):

```suggestion
%define make_common_args EXTRA_CFLAGS="-Wno-error" NORPATH=1 BUILD_EXAMPLES=n BUILD_BENCHMARKS=n
```

2024-09-04 19:07 UTC, brianjmurrell commented on pmdk.spec
> -%bcond_with ndctl
Any answer to this question?

2024-09-04 19:43 UTC, grom72 commented on pmdk.spec
> +%define make_common_args %{_make_common_args}
Done

2024-10-15 16:17 UTC, grom72 commented on pmdk.spec
> -%bcond_with ndctl
There is no plan to support PMDK w/o NDCTL in the future. NDCTL is used by the PMDK to implement PMem RAS features.

2024-10-15 17:06 UTC, brianjmurrell commented
There are a **lot** of failures in the downstream DAOS testing on both `master` and `release/2.6`.  Are we **sure** these are unrelated to this PR?  I have a hard time imagining that the tip of `release/2.6` has 147 failures on it.

2024-10-16 06:29 UTC, grom72 commented
> There are a **lot** of failures in the downstream DAOS testing on both `master` and `release/2.6`. Are we **sure** these are unrelated to this PR? I have a hard time imagining that the tip of `release/2.6` has 147 failures on it.

`release/2.6` failures are expected in combination when the old DAOS (w/o NDCTL support) DAOS is used w/ PMDK that uses NDCTL:
`*ERROR* usc_ndctl.c:  55: pmem2_source_device_usc: Unsafe shutdown count is not supported for this source`
All errors are related to tests on VMs when NDCTL-related features must be intentionally disabled as simulated PMem (RAM-based) does not support it => see https://github.com/daos-stack/daos/pull/14371#issue-2296987020: `PMEMOBJ_CONF=sds.at_create=0`

`master`'s tests failures are related to md-on-ssd, but let us wait for the next validation cycle

2024-10-16 16:34 UTC, brianjmurrell commented
> `release/2.6` failures are expected in combination when the old DAOS (w/o NDCTL support) DAOS is used w/ PMDK that uses NDCTL: `*ERROR* usc_ndctl.c: 55: pmem2_source_device_usc: Unsafe shutdown count is not supported for this source` All errors are related to tests on VMs when NDCTL-related features must be intentionally disabled as simulated PMem (RAM-based) does not support it => see [daos-stack/daos#14371 (comment)](https://github.com/daos-stack/daos/pull/14371#issue-2296987020): `PMEMOBJ_CONF=sds.at_create=0`

Regardless of why, what this is telling us is that as soon as we land this, we are going to break both `relelase/2.6` future releases and all ongoing (i.e. daily/weekly/etc.) testing on `relelase/2.6`.  We cannot do that as we are just throwing >100 "known failures" on to the pile and further creating a situation that will need to be resolved to make another 2.6.x release (which we might be forced to do to fix a bug, even if we currently have no plans for a 2.6.2).

So ultimately, one way or another, we need to resolve the >100 test failures that we are going to introduce to `release/2.6` by landing this.  Should `relelase/2.6` not get whatever is necessary for it to work with this new _pmdk_ backported to it?

2024-10-22 17:06 UTC, grom72 commented
> > `release/2.6` failures are expected in combination when the old DAOS (w/o NDCTL support) DAOS is used w/ PMDK that uses NDCTL: `*ERROR* usc_ndctl.c: 55: pmem2_source_device_usc: Unsafe shutdown count is not supported for this source` All errors are related to tests on VMs when NDCTL-related features must be intentionally disabled as simulated PMem (RAM-based) does not support it => see [daos-stack/daos#14371 (comment)](https://github.com/daos-stack/daos/pull/14371#issue-2296987020): `PMEMOBJ_CONF=sds.at_create=0`
> 
> Regardless of why, what this is telling us is that as soon as we land this, we are going to break both `relelase/2.6` future releases and all ongoing (i.e. daily/weekly/etc.) testing on `relelase/2.6`. We cannot do that as we are just throwing >100 "known failures" on to the pile and further creating a situation that will need to be resolved to make another 2.6.x release (which we might be forced to do to fix a bug, even if we currently have no plans for a 2.6.2).
> 
> So ultimately, one way or another, we need to resolve the >100 test failures that we are going to introduce to `release/2.6` by landing this. Should `relelase/2.6` not get whatever is necessary for it to work with this new _pmdk_ backported to it?

@brianjmurrell , please take a look at https://github.com/daos-stack/daos/pull/15203

2024-10-23 12:39 UTC, janekmi approved these changes

2024-10-23 12:40 UTC, grom72 commented
Final validation (+ ticket for failing tests):
master:
https://build.hpdd.intel.com/job/daos-stack/job/daos/job/ci-daos-stack-pmdk-PR-38-master/32/testReport
+ https://daosio.atlassian.net/browse/DAOS-16503
2.6:
https://build.hpdd.intel.com/job/daos-stack/job/daos/job/ci-daos-stack-pmdk-PR-38-release-2.6/25/testReport/
+ https://daosio.atlassian.net/browse/DAOS-16171
+ https://daosio.atlassian.net/browse/DAOS-14982

2024-10-28 15:52 UTC, brianjmurrell approved these changes

2024-10-28 18:24 UTC, merged

2024-10-28 18:25 UTC, brianjmurrell commented
@grom72 Landed.  Please delete the downstream testing branches that failed their testing.

2024-10-28 20:18 UTC, grom72 commented
> @grom72 Landed. Please delete the downstream testing branches that failed their testing.

Done