PMDK release 2.1.0 w/o NDCTL enabled
daos-stack/pmdk-pkg pull request #39
Opened 2024-05-21 13:57 UTC by osalyk

2024-05-21 14:09 UTC, brianjmurrell requested changes
Your PR title is saying the version to build is 2.1.0 but https://github.com/daos-stack/pmdk/blob/27ef152155d82b128d198690d9d9cdfa22862dc5/pmdk.spec#L18-L20 will result in 2.0.0 being built.

Additionally, every `*.spec` file change needs a `%changelog` entry and either a `Version:` update and/or a `Release:` update as well.

2024-05-21 15:12 UTC, grom72 commented on pmdk.spec
`# --with ndctl` instead of `# --with | --without ndctl`

2024-05-21 15:45 UTC, grom72 requested changes

2024-05-21 15:45 UTC, grom72 commented on pmdk.spec
> +    %define make_common_args %{_make_common_args} NDCTL_ENABLE=n
```
%define make_common_args %{_make_common_args} NDCTL_ENABLE=n PMEMOBJ_IGNORE_DIRTY_SHUTDOWN=y PMEMOBJ_IGNORE_BAD_BLOCKS=y
```

2024-05-21 19:00 UTC, grom72 commented
> Your PR title is saying the version to build is 2.1.0 but
> 
> https://github.com/daos-stack/pmdk/blob/27ef152155d82b128d198690d9d9cdfa22862dc5/pmdk.spec#L18-L20
> 
> will result in 2.0.0 being built.
> Additionally, every `*.spec` file change needs a `%changelog` entry and either a `Version:` update and/or a `Release:` update as well.

Fixed by rebasing on the top of #37

2024-05-22 06:41 UTC, osalyk commented on pmdk.spec
> +    %define make_common_args %{_make_common_args} NDCTL_ENABLE=n
Done.

2024-05-22 06:41 UTC, osalyk commented on pmdk.spec
Done.

2024-05-22 08:34 UTC, grom72 requested changes

2024-05-22 08:34 UTC, grom72 commented on pmdk.spec
>  %define min_ndctl_ver 63
# by default build without ndctl, unless explicitly enabled
%bcond_with ndctl

2024-05-22 08:36 UTC, osalyk commented on pmdk.spec
>  %define min_ndctl_ver 63
Done.

2024-05-22 14:46 UTC, merged