New LICENSE file as expected by OpenSSF Scorecard
daos-stack/pmdk-pkg pull request #40
Opened 2024-08-28 13:04 UTC by grom72

New LICENSE file as expected by OpenSSF Scorecard

2024-08-28 13:21 UTC, brianjmurrell reviewed
Looks good, ~~but should you also add the other files (`SECURITY.md` at least) that IPAS is requiring by the end of this quarter?~~ NVM, I see that IPAS added https://github.com/daos-stack/.github/blob/master/SECURITY.md which I guess covers all of our projects at once.

2024-08-28 13:33 UTC, brianjmurrell submitted a review, later dismissed

2024-09-20 20:08 UTC, ryon-jensen submitted a review, later dismissed

2024-09-20 20:08 UTC, ryon-jensen commented on Jenkinsfile
> +@Library(value="pipeline-lib@grom72/SRE-2453") _
this will of course need to change before landing.

2024-09-24 20:23 UTC, grom72 commented on Jenkinsfile
> +@Library(value="pipeline-lib@grom72/SRE-2453") _
Done

2024-09-24 20:47 UTC, ryon-jensen approved these changes, later dismissed

2024-09-25 12:40 UTC, brianjmurrell requested changes
Why are the `Jenkinsfile` and the `LICENCE` file referring to **BSD-2-Clause-Patent**/**BSD-2-Clause Plus Patent License** but the other changed files here refer to **BSD-3-Clause**?

2024-09-25 12:40 UTC, brianjmurrell commented on pmdk.spec
Shouldn't https://github.com/daos-stack/pmdk/blob/cc5cb682e8255a877735523220ee573fb3395dba/pmdk.spec#L47 be **BSD-2-Clause-Patent** or **BSD-3-Clause**?  But TBH, given the overall concerns with having different licenses throughout this file, I'm thoroughly confused which it should be.

2024-09-26 07:37 UTC, grom72 commented on pmdk.spec
My mistake. It should be BSD-2-Clause-Paten

2024-10-04 08:37 UTC, janekmi requested changes

2024-10-04 08:37 UTC, janekmi commented on pmdk.rpmlintrc
> +# Copyright (c) 2019-2024 Intel Corporation
```suggestion
# Copyright (c) 2022-2024 Intel Corporation
```

2024-10-04 08:53 UTC, janekmi requested changes

2024-10-04 08:53 UTC, janekmi commented on pmdk.spec
> +# Copyright (c) 2019-2024 Intel Corporation
Assuming this file started as a copy-paste from the PMDK repo I believe the correct copyright range is as follows:

```suggestion
# Copyright (c) 2017-2024 Intel Corporation
```

2024-10-04 09:46 UTC, grom72 commented on pmdk.spec
> +# Copyright (c) 2019-2024 Intel Corporation
Done

2024-10-04 09:46 UTC, grom72 commented on pmdk.rpmlintrc
> +# Copyright (c) 2019-2024 Intel Corporation
Done

2024-10-04 10:55 UTC, janekmi approved these changes

2024-10-04 11:04 UTC, osalyk approved these changes

2024-10-07 17:55 UTC, brianjmurrell requested changes

2024-10-07 17:55 UTC, brianjmurrell commented on pmdk.spec
> +License:    BSD-3-Clause
This seems to contradict what you [said previously](https://github.com/daos-stack/pmdk/pull/40/files#r1776539422).

2024-10-08 05:53 UTC, grom72 commented on pmdk.spec
> +License:    BSD-3-Clause
Fix the comment above. PMDK is distributed with the BSD-3-Clause license.
DAOS's spec that creates PMDK rpm is distributed under the BSD-2-Clause-Patent license.

2024-10-08 14:08 UTC, janekmi commented on pmdk.spec
> +License:    BSD-3-Clause
I would say, it is correct. @brianjmurrell do you have any further doubts?

2024-10-08 14:20 UTC, brianjmurrell approved these changes

2024-10-08 14:20 UTC, brianjmurrell commented on pmdk.spec
> +License:    BSD-3-Clause
Seems fine.  Confusion between PMDK and the RPM packaging of it.

2024-10-08 14:30 UTC, merged