Create scorecard.yml
daos-stack/pmdk-pkg pull request #41
Opened 2024-08-29 12:34 UTC by grom72

Create scorecard workflow.

Doc-only: true.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/daos-stack/pmdk-pkg/41)

2024-09-03 18:40 UTC, brianjmurrell requested changes

2024-09-03 18:40 UTC, brianjmurrell commented on .github/workflows/scorecard.yml
> +
We should add `pull_request:` here so that issues are found in PRs, not once they have landed to master.

```suggestion
  pull_request:

```

2024-09-03 18:40 UTC, brianjmurrell commented on .github/workflows/scorecard.yml
> +permissions: read-all
Is read permission needed here?  The DAOS version of this workflow uses:

```
permissions: {}
```

and AFAICT seems to be functioning correctly, but maybe I am missing something.

2024-09-04 12:51 UTC, grom72 commented on .github/workflows/scorecard.yml
> +
Done, however, it does not make big sense as the scorecard dose does not produce yes/no judgement

2024-09-04 12:51 UTC, grom72 commented on .github/workflows/scorecard.yml
> +permissions: read-all
Done

2024-09-04 13:26 UTC, brianjmurrell commented on .github/workflows/scorecard.yml
> +
IIRC, it does flag errors that are found.  You could try introducing one and confirm.

2024-09-09 12:22 UTC, brianjmurrell requested changes
I think before we land this, we need to understand how it will operate on a PR if a Scorecard issue is introduced so that we understand the UX our users will face.

2025-10-08 09:24 UTC, osalyk approved these changes

2025-11-19 13:29 UTC, grom72 commented
This PR is no longer valid as we are going to archive this project.

2025-11-19 13:29 UTC, closed without merging