DAOS-16660 No error message on intentional pmemobj transaction abort
daos-stack/pmdk-pkg pull request #43
Opened 2024-10-04 11:22 UTC by grom72

2024-11-06 11:13 UTC, janekmi requested changes

2024-11-06 11:13 UTC, janekmi commented on pmdk.spec
> +- use patch to avoid anoing error message on PMDK used with non-PMem HW.
```suggestion
- Apply patches to silence annoying error messages on:
  - an intentional transaction abort and
  - PMDK being used with non-PMem HW.
```

2024-11-06 11:13 UTC, janekmi commented on pmdk.spec
> +
```suggestion

```

2024-11-06 11:13 UTC, janekmi commented on pmdk.spec
> +* Wed Oct 23 2024  Tomasz Gromadzki <tomasz.gromadzki@intel.com> - 2.1.0-3
```suggestion
* Wed Nov 06 2024  Tomasz Gromadzki <tomasz.gromadzki@intel.com> - 2.1.0-3
```

2024-11-06 11:13 UTC, janekmi commented on pmdk.spec
> +%endif
What is the role of this addition?

2024-11-06 11:13 UTC, janekmi commented on debian/changelog
> +  * Use patch to avoid anoing error message on PMDK used with non-PMem HW.
```suggestion
  * Apply patches to silence annoying error messages on:
    * an intentional transaction abort and
    * PMDK being used with non-PMem HW.
```

2024-11-06 11:13 UTC, janekmi commented on debian/changelog
> + -- Tomasz Gromadzki <tomasz.gromadzki@intel.com>  Thu, 24 Oct 2024 10:00:00 +0000
```suggestion
 -- Tomasz Gromadzki <tomasz.gromadzki@intel.com>  Thu, 06 Nov 2024 10:00:00 +0000
```

2024-11-06 11:13 UTC, janekmi commented on debian/changelog
> +
```suggestion

```

2024-11-06 12:11 UTC, grom72 commented on debian/changelog
> +  * Use patch to avoid anoing error message on PMDK used with non-PMem HW.
Done

2024-11-06 12:11 UTC, grom72 commented on debian/changelog
> + -- Tomasz Gromadzki <tomasz.gromadzki@intel.com>  Thu, 24 Oct 2024 10:00:00 +0000
Done

2024-11-06 12:12 UTC, grom72 commented on pmdk.spec
> +
Done

2024-11-06 12:19 UTC, grom72 commented on pmdk.spec
> +- use patch to avoid anoing error message on PMDK used with non-PMem HW.
Done

2024-11-06 12:38 UTC, janekmi submitted a review, later dismissed

2024-11-06 12:52 UTC, brianjmurrell approved these changes

2024-11-13 06:53 UTC, grom72 commented
All tests have passed on: 
- `release/2.6`: https://build.hpdd.intel.com/job/daos-stack/job/daos/job/ci-daos-stack-pmdk-PR-43-release-2.6/13/
- `master`: https://build.hpdd.intel.com/job/daos-stack/job/daos/job/ci-daos-stack-pmdk-PR-43-master/16/

2024-11-18 14:35 UTC, brianjmurrell commented
> All tests have passed on:
> 
> * `release/2.6`: [build.hpdd.intel.com/job/daos-stack/job/daos/job/ci-daos-stack-pmdk-PR-43-release-2.6/13](https://build.hpdd.intel.com/job/daos-stack/job/daos/job/ci-daos-stack-pmdk-PR-43-release-2.6/13/)

Nice.

> * `master`: [build.hpdd.intel.com/job/daos-stack/job/daos/job/ci-daos-stack-pmdk-PR-43-master/16](https://build.hpdd.intel.com/job/daos-stack/job/daos/job/ci-daos-stack-pmdk-PR-43-master/16/)

Latest [master test run](https://jenkins-1.wolf.hpdd.intel.com:9090/blue/organizations/jenkins/daos-stack%2Fdaos/detail/ci-daos-stack-pmdk-PR-43-master/17/pipeline) [failed](https://jenkins-1.wolf.hpdd.intel.com:9090/blue/organizations/jenkins/daos-stack%2Fdaos/detail/ci-daos-stack-pmdk-PR-43-master/17/tests/) in `test_ior_intercept_libioil`.  Is that a known failure?  If so, I will add it and it's ticket to the skiplist for landing so that maybe we get a green/passing landing.

2024-11-25 15:10 UTC, brianjmurrell commented
@grom72 Any thoughts on my [previous question](https://github.com/daos-stack/pmdk/pull/43#issuecomment-2483234319)?

2025-01-16 07:10 UTC, grom72 commented
All required tests pass:
https://build.hpdd.intel.com/job/daos-stack/job/pmdk/job/PR-43/19/pipeline-graph/ (https://build.hpdd.intel.com/job/daos-stack/job/daos/job/ci-daos-stack-pmdk-PR-43-master/36/pipeline-graph/)
`master` branch tests pass in the additional downstream run:
https://build.hpdd.intel.com/job/daos-stack/job/daos/job/ci-daos-stack-pmdk-PR-43-master/37/pipeline-graph/

2025-01-16 17:44 UTC, janekmi approved these changes

2025-01-17 12:06 UTC, merged